# https://taskfile.dev

version: '3'

env:
  MODULE_PATH: github.com/barnowlsnest/pgqs-tenants

tasks:
  update:
    cmds:
      - go mod tidy

  lint:
    cmds:
      - go vet ./...
      - go fmt ./...
      - golangci-lint run --fix

  build:
    cmds:
      - go build .

  test:
    cmds:
      - go clean -testcache
      - go test -v -race -timeout 5m ./...