# https://taskfile.dev

version: '3'

env:
  MODULE_PATH: github.com/barnowlsnest/pgqs-tenants

tasks:
  update:
    env:
      GOPRIVATE: github.com/barnowlsnest/*
    cmds:
      - go mod tidy

  lint:
    cmds:
      - go vet ./...
      - go fmt ./...
      - goimports -l -e -w ./
      - golangci-lint run --fix

  build:
    cmds:
      - go build .

  unit-tests:
    env:
      GOPRIVATE: github.com/barnowlsnest/*
    cmds:
      - go clean -testcache
      - go test -v -race -timeout 5m ./...

  integration-tests:
    env:
      GOPRIVATE: github.com/barnowlsnest/*
    cmds:
      - go clean -testcache
      - go test -v -race -timeout 10m -tags integration ./...
